--
-- Author: Reyn
-- Date: 2016-06-18 15:41:04
--
require('init')

local s1 = Stack(10)
console_colorful("=======push=======")
console_colorful("sapce = " .. s1:space())
print(s1:push('a'))
s1.serial()
print(s1:push('b'))
s1.serial()
print(s1:push('c'))
s1.serial()
print(s1:push('d'))
s1.serial()
print(s1:push('e'))
s1.serial()
print(s1:push('f'))
s1.serial()
print(s1:push('g'))
s1.serial()
print(s1:push('h'))
s1.serial()
print(s1:push('i'))
s1.serial()
print(s1:push('j'))
s1.serial()
print(s1:push('k'))
s1.serial()
print(s1:push('l'))
s1.serial()
print(s1:push('m'))
s1.serial()
print(s1:push('n'))
s1.serial()
print(s1:push('o'))
s1.serial()
s1:setSpace(15)
console_colorful("sapce = " .. s1:space())
print(s1:push('p'))
s1.serial()
print(s1:push('q'))
s1.serial()
print(s1:push('r'))
s1.serial()
console_colorful("=======pop=======")
console_colorful("len = " .. s1:len())
console_colorful("space = " .. s1:space())
print(s1:pop())
s1.serial()
print(s1:pop())
s1.serial()
print(s1:pop())
s1.serial()
print(s1:pop())
s1.serial()
print(s1:pop())
s1.serial()
print(s1:pop())
s1.serial()
console_colorful("len = ".. s1:len())
console_colorful("sapce = " ..s1:space())