--
-- Author: Reyn
-- Date: 2016-06-18 15:41:04
--
require('init')

local q1 = Queue(10)
console_colorful("=======enqueue=======")
console_colorful("sapce = " .. q1:space())
print(q1:enqueue('a'))
q1.serial()
print(q1:enqueue('b'))
q1.serial()
print(q1:enqueue('c'))
q1.serial()
print(q1:enqueue('d'))
q1.serial()
print(q1:enqueue('e'))
q1.serial()
print(q1:enqueue('f'))
q1.serial()
print(q1:enqueue('g'))
q1.serial()
print(q1:enqueue('h'))
q1.serial()
print(q1:enqueue('i'))
q1.serial()
print(q1:enqueue('j'))
q1.serial()
print(q1:enqueue('k'))
q1.serial()
print(q1:enqueue('l'))
q1.serial()
print(q1:enqueue('m'))
q1.serial()
print(q1:enqueue('n'))
q1.serial()
print(q1:enqueue('o'))
q1.serial()
q1:setSpace(15)
console_colorful("sapce = " .. q1:space())
print(q1:enqueue('p'))
q1.serial()
print(q1:enqueue('q'))
q1.serial()
print(q1:enqueue('r'))
q1.serial()
console_colorful("=======dequeue=======")
console_colorful("len = " .. q1:len())
console_colorful("space = " .. q1:space())
print(q1:dequeue())
q1.serial()
print(q1:dequeue())
q1.serial()
print(q1:dequeue())
q1.serial()
print(q1:dequeue())
q1.serial()
print(q1:dequeue())
q1.serial()
print(q1:dequeue())
q1.serial()
console_colorful("len = " .. q1:len())
console_colorful("sapce = " .. q1:space())